language: php

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - mysql -e "create database IF NOT EXISTS mn_tv_listings;" -uroot

install:
    - composer self-update
    - composer install

script:
    - phpunit --coverage-text
