language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
    - composer self-update
    - composer install

before_script:
    - php vendor/bin/doctrine orm:schema-tool:create
    - php vendor/bin/doctrine orm:schema-tool:update --force

script:
    - phpunit --coverage-text

after_script:
    - php vendor/bin/doctrine orm:schema-tool:drop --force
